### ISSUE TITLE
打开之前的drawio文件，更改之后无法保存

### ISSUE THREAD

**Issue by yxy823** [macvip/widget-cover-drawio#1]
打开之前的drawio文件，更改之后无法保存
    ![image](https://user-images.githubusercontent.com/38773494/160231339-8a1e98fc-1f7b-4c5c-ad8f-1912f310655f.png)

**Comment by macvip** [comment]
请问之前保存的 drawio 文件，是否是 svg 格式？cover-drawio 暂时只支持 svg 格式图片显示。

**Comment by macvip** [comment]
drawio 挂件的问题，请直接反馈给原作者
